#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-ggpubr
Version  : 0.6.0
Release  : 2
URL      : https://cran.r-project.org/src/contrib/ggpubr_0.6.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ggpubr_0.6.0.tar.gz
Summary  : 'ggplot2' Based Publication Ready Plots
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-cowplot
Requires: R-dplyr
Requires: R-ggplot2
Requires: R-ggrepel
Requires: R-ggsci
Requires: R-ggsignif
Requires: R-glue
Requires: R-gridExtra
Requires: R-magrittr
Requires: R-polynom
Requires: R-purrr
Requires: R-rlang
Requires: R-rstatix
Requires: R-scales
Requires: R-tibble
Requires: R-tidyr
BuildRequires : R-cowplot
BuildRequires : R-dplyr
BuildRequires : R-ggplot2
BuildRequires : R-ggrepel
BuildRequires : R-ggsci
BuildRequires : R-ggsignif
BuildRequires : R-glue
BuildRequires : R-gridExtra
BuildRequires : R-magrittr
BuildRequires : R-polynom
BuildRequires : R-purrr
BuildRequires : R-rlang
BuildRequires : R-rstatix
BuildRequires : R-scales
BuildRequires : R-tibble
BuildRequires : R-tidyr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
visualization in R. However the default generated plots requires some formatting
    before we can send them for publication. Furthermore, to customize a 'ggplot',
    the syntax is opaque and this raises the level of difficulty for researchers
    with no advanced R programming skills. 'ggpubr' provides some easy-to-use
    functions for creating and customizing 'ggplot2'- based publication ready plots.

%prep
%setup -q -n ggpubr

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713980420

%install
export SOURCE_DATE_EPOCH=1713980420
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ggpubr/DESCRIPTION
/usr/lib64/R/library/ggpubr/INDEX
/usr/lib64/R/library/ggpubr/Meta/Rd.rds
/usr/lib64/R/library/ggpubr/Meta/data.rds
/usr/lib64/R/library/ggpubr/Meta/features.rds
/usr/lib64/R/library/ggpubr/Meta/hsearch.rds
/usr/lib64/R/library/ggpubr/Meta/links.rds
/usr/lib64/R/library/ggpubr/Meta/nsInfo.rds
/usr/lib64/R/library/ggpubr/Meta/package.rds
/usr/lib64/R/library/ggpubr/NAMESPACE
/usr/lib64/R/library/ggpubr/NEWS.md
/usr/lib64/R/library/ggpubr/R/ggpubr
/usr/lib64/R/library/ggpubr/R/ggpubr.rdb
/usr/lib64/R/library/ggpubr/R/ggpubr.rdx
/usr/lib64/R/library/ggpubr/data/Rdata.rdb
/usr/lib64/R/library/ggpubr/data/Rdata.rds
/usr/lib64/R/library/ggpubr/data/Rdata.rdx
/usr/lib64/R/library/ggpubr/demo-data/housetasks.txt
/usr/lib64/R/library/ggpubr/help/AnIndex
/usr/lib64/R/library/ggpubr/help/aliases.rds
/usr/lib64/R/library/ggpubr/help/ggpubr.rdb
/usr/lib64/R/library/ggpubr/help/ggpubr.rdx
/usr/lib64/R/library/ggpubr/help/paths.rds
/usr/lib64/R/library/ggpubr/html/00Index.html
/usr/lib64/R/library/ggpubr/html/R.css
/usr/lib64/R/library/ggpubr/images/background-image.png
/usr/lib64/R/library/ggpubr/tests/testthat.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-add_stat_label.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-as_npc.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-check_data.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-compare_means.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-create_aes.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-facet.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-geom_pwc.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-get_coord.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-ggadjust_pvalue.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-ggboxplot.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-gghistogram.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-ggscatter.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-ggstripchart.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-ggtext.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-stat_anova_test.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-stat_compare_means.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-stat_friedman_test.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-stat_kruskal_test.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-stat_welch_anova_test.R
/usr/lib64/R/library/ggpubr/tests/testthat/test-utils-tidyr.R
